
postgres:
  connection: user=postgres password=postgres host=localhost port=5432 sslmode=disable
  table: logs
  column: log
  max_open_connections: 10
  verbose: no

nsq:
  topic: logs
  channel: postgres_logger
  nsqd: localhost:4150
  max_attempts: 5
  msg_timeout: 15s
  max_in_flight: 300
  concurrency: 50
