
postgres:
  connection: user=tj password=sloth host=192.168.59.103 port=5432 sslmode=disable
  table: logs
  column: log
  max_open_connections: 10
  verbose: no

nsq:
  topic: logs
  channel: postgres_logger
  nsqd: 192.168.59.103:4150
  max_attempts: 5
  msg_timeout: 15s
  max_in_flight: 300
  concurrency: 50
