
nsqd:
  image: nsqio/nsq
  command: /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
  ports:
    - "4150:4150"
    - "4151:4151"
  links:
    - nsqlookupd

nsqadmin:
  image: nsqio/nsq
  command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
  ports:
    - "4171:4171"
  links:
    - nsqlookupd
    - nsqd

nsqlookupd:
  image: nsqio/nsqlookupd
  command: nsqlookupd
  ports:
    - "4160:4160"
    - "4161:4161"

postgres:
  image: postgres:9.4
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres